// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using sprint3.NET.Database.Persistencia;

#nullable disable

namespace sprint3.NET.Database.Migrations
{
    [DbContext(typeof(FIAPDbContext))]
    [Migration("20240915183410_CriandoTabelas")]
    partial class CriandoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sprint3.NET.Database.Models.Agricultor", b =>
                {
                    b.Property<int>("Agricultor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Agricultor_Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Agricultor_Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("TB_Agricultores_sprint3", (string)null);
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Fazenda", b =>
                {
                    b.Property<int>("Fazenda_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fazenda_Id"));

                    b.Property<int>("AgricultorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<decimal>("TamanhoHectares")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Fazenda_Id");

                    b.HasIndex("AgricultorId");

                    b.ToTable("TB_Fazendas_sprint3", (string)null);
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Safra", b =>
                {
                    b.Property<int>("Safra_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Safra_Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cultura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Safra_Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("Safra");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Solo", b =>
                {
                    b.Property<int>("Solo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Solo_Id"));

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("NivelNitrogenio")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("NivelPotassio")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("PH")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TipoSolo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Solo_Id");

                    b.HasIndex("FazendaId");

                    b.ToTable("Solo");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Usuario", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usuario_Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Usuario_Id");

                    b.ToTable("TB_Usuarios_sprint3", (string)null);
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Agricultor", b =>
                {
                    b.HasOne("sprint3.NET.Database.Models.Usuario", "Usuario")
                        .WithOne("Agricultor")
                        .HasForeignKey("sprint3.NET.Database.Models.Agricultor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Fazenda", b =>
                {
                    b.HasOne("sprint3.NET.Database.Models.Agricultor", "Agricultor")
                        .WithMany("Fazendas")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Safra", b =>
                {
                    b.HasOne("sprint3.NET.Database.Models.Fazenda", "Fazenda")
                        .WithMany("Safras")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Solo", b =>
                {
                    b.HasOne("sprint3.NET.Database.Models.Fazenda", "Fazenda")
                        .WithMany("Solos")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Agricultor", b =>
                {
                    b.Navigation("Fazendas");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Fazenda", b =>
                {
                    b.Navigation("Safras");

                    b.Navigation("Solos");
                });

            modelBuilder.Entity("sprint3.NET.Database.Models.Usuario", b =>
                {
                    b.Navigation("Agricultor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
